name: cpp-build

on: [pull_request]

jobs:
  cpp-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Prepare
        run: |
          apt install arm-none-eabi-gcc
      - name: build
        run: make
