name: cpp-build

on:
  pull_request:
    branches: [ master ]

jobs:
  arm-build:
    runs-on: ubuntu-latest
    steps:
      - name: arm-none-eabi-gcc build
      - uses: fiam/arm-none-eabi-gcc@v1
        with:
          release: '9-2019-q4'
      - uses: actions/checkout@master
      - run: make
